title: "十二毫升的爱丽丝"
author: "sandtears"
email: "me@sandtears.com"
description: >
  梦游仙境的爱丽丝，在呓语些什么？

baseurl: ""
url: "https://blog.sandtears.com"
storage_url: "https://storage.sandtears.com"
rss: rss
show_excerpts: false
date_format: "%b %-d, %Y"
telegram_username: "Arisu12"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-toc

exclude: ['publish.sh', 'upload_pic.sh']
